version: '3'
services:
  artbyai-py:
    image: artbyai-py
    container_name: artbyai-py
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./log:/app/log
      - ./config.yaml:/app/config.yaml

